modLoader="javafml"
loaderVersion="[13,)"
#updateJSONURL=""
issueTrackerURL="https://github.com/Team-Fruit/Emojicord/issues?q=is%3Aissue"
displayURL="https://www.curseforge.com/minecraft/mc-mods/emojicord"
logoFile="logo.png"
credits="Crafted by TeamFruit, Thanks for Discord Emojis."
authors="TeamFruit"

[[mods]]
modId="emojicord"
version="${file.jarVersion}"
displayName="Emojicord"
displayURL="https://www.teamfruit.net/"
logoFile="logo.png"
authors="Kamesuta"
description='''
Discord Emojis in Minecraft
'''

[[dependencies.emojicord]]
    modId="forge"
    mandatory=false
    versionRange="[24.0.42,)"
    ordering="NONE"
    side="CLIENT"