modLoader="javafml"
loaderVersion="[13,)"
updateJSONURL="https://raw.githubusercontent.com/Team-Fruit/Emojicord/update/update.json"
issueTrackerURL="https://github.com/Team-Fruit/Emojicord/issues?q=is%3Aissue"
displayURL="https://emojicord.teamfruit.net/download/"
logoFile="logo.png"
credits="2019 TeamFruit"
authors="TeamFruit"

[[mods]]
modId="emojicord"
version="${file.jarVersion}"
displayName="Emojicord"
displayURL="https://emojicord.teamfruit.net/"
logoFile="logo.png"
authors="Kamesuta"
description='''
Discord Emojis in Minecraft
'''

[[dependencies.emojicord]]
    modId="forge"
    mandatory=false
    versionRange="[24.0.42,)"
    ordering="NONE"
    side="CLIENT"